# K Fold Cross Validation

importing required libraries

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

importing Dataset from sklearn predefined datasets

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.2)

Trying Logistic Regression on Data

In [12]:
logr = LogisticRegression()
logr.fit(x_train, y_train)
logr.score(x_test,y_test)

c:\users\aman asati\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

Trying SVC on Data

In [13]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test,y_test)

0.9805555555555555

Trying Random Forest on Data

In [14]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9694444444444444

#### These all above algorithms tried and re-run many times. Instead of doing this we will use K Fold Cross Validation

In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
for train_index, test_index in kf.split([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]):
    print(train_index, test_index)

[ 5  6  7  8  9 10 11 12 13 14] [0 1 2 3 4]
[ 0  1  2  3  4 10 11 12 13 14] [5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14]


In [21]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train,y_train)
    return model.score(x_test, y_test)

In [22]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

c:\users\aman asati\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

In [24]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9805555555555555

In [25]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9666666666666667

In [26]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [28]:
scores_lr = []
scores_svm = []
scores_rd = []

for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rd.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

c:\users\aman asati\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\aman asati\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-lear

In [29]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [30]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [31]:
scores_rd

[0.9398998330550918, 0.9482470784641068, 0.9198664440734557]

In [33]:
from sklearn.model_selection import cross_val_score

In [34]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

c:\users\aman asati\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\aman asati\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-lear

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [35]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

##### Parameter Tuning

In [38]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.92777778, 0.88888889, 0.94986072, 0.95543175, 0.9275766 ])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target)

array([0.90277778, 0.89444444, 0.94986072, 0.91364903, 0.87743733])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target)

array([0.92777778, 0.91388889, 0.9637883 , 0.96100279, 0.91643454])